hw2 : commonGrade.cmo hw6_2.cmo
	ocaml commonGrade.cmo hw6_2.cmo hw6_2_grade.ml
hw3 : commonGrade.cmo hw6_3.cmo
	ocaml commonGrade.cmo hw6_3.cmo hw6_3_grade.ml
hw4 : commonGrade.cmo hw6_4.cmo
	ocaml commonGrade.cmo hw6_4.cmo hw6_4_grade.ml
hw5 : commonGrade.cmo hw6_5.cmo
	ocaml commonGrade.cmo hw6_5.cmo hw6_5_grade.ml
hw6 : commonGrade.cmo hw6_6.cmo
	ocaml commonGrade.cmo hw6_6.cmo hw6_6_grade.ml
hw7 : commonGrade.cmo hw6_7.cmo
	ocaml commonGrade.cmo hw6_7.cmo hw6_7_grade.ml
hw9 : commonGrade.cmo hw6_9.cmo
	ocaml commonGrade.cmo hw6_9.cmo hw6_9_grade.ml

commonGrade.cmo : commonGrade.ml
	ocamlc commonGrade.ml

hw6_2.cmo : hw6_2.ml
	ocamlc hw6_2.ml
hw6_3.cmo : hw6_3.ml
	ocamlc hw6_3.ml
hw6_4.cmo : hw6_4.ml
	ocamlc hw6_4.ml
hw6_5.cmo : hw6_5.ml
	ocamlc hw6_5.ml
hw6_6.cmo : hw6_6.ml
	ocamlc hw6_6.ml
hw6_7.cmo : hw6_7.ml
	ocamlc hw6_7.ml
hw6_9.cmo : hw6_9.ml
	ocamlc hw6_9.ml

clean :
	rm -f *.cmo *.exe *.cmi
