hw1 : commonGrade.cmo hw8_1.cmo
	ocaml commonGrade.cmo hw8_1.cmo hw8_1_grade.ml
hw2 : commonGrade.cmo hw8_2.cmo
	ocaml commonGrade.cmo hw8_2.cmo hw8_2_grade.ml
hw3 : commonGrade.cmo hw8_3.cmo
	ocaml commonGrade.cmo hw8_3.cmo hw8_3_grade.ml
hw4 : commonGrade.cmo hw8_4.cmo
	ocaml commonGrade.cmo hw8_4.cmo hw8_4_grade.ml
hw4_2 : commonGrade.cmo hw8_4.cmo
	ocaml commonGrade.cmo hw8_4.cmo hw8_4_grade_2.ml
hw3_new : commonGrade.cmo hw8_3.cmo
	ocaml commonGrade.cmo hw8_3.cmo hw8_3_grade_new.ml
hw1_actual : commonGrade.cmo hw8_1.cmo
	ocaml commonGrade.cmo hw8_1.cmo hw8_1_actualgrade.ml
hw2_actual : commonGrade.cmo hw8_2.cmo
	ocaml commonGrade.cmo hw8_2.cmo hw8_2_actualgrade.ml
hw3_actual : commonGrade.cmo hw8_3.cmo
	ocaml commonGrade.cmo hw8_3.cmo hw8_3_actualgrade.ml
hw4_actual : commonGrade.cmo hw8_4.cmo
	ocaml commonGrade.cmo hw8_4.cmo hw8_4_actualgrade.ml

commonGrade.cmo : commonGrade.ml
	ocamlc commonGrade.ml

hw8_1.cmo : hw8_1.ml
	ocamlc hw8_1.ml
hw8_2.cmo : hw8_2.ml
	ocamlc hw8_2.ml
hw8_3.cmo : hw8_3.ml
	ocamlc hw8_3.ml
hw8_4.cmo : hw8_4.ml
	ocamlc hw8_4.ml

clean :
	rm -f *.cmo *.exe *.cmi
