t : commonGrade.cmo t.cmo t_actualgrade.ml
	ocaml commonGrade.cmo t.cmo t_actualgrade.ml

i : t.cmo interpreter.ml
	ocaml t.cmo interpreter.ml

commonGrade.cmo : commonGrade.ml
	ocamlc commonGrade.ml

t.cmo : t.ml
	ocamlc t.ml
