prj1_actual : commonGrade.cmo prj1.cmo prj1_actualgrade.ml
	ocaml commonGrade.cmo prj1.cmo prj1_actualgrade.ml

commonGrade.cmo : commonGrade.ml
	ocamlc commonGrade.ml

prj1.cmo : prj1.ml
	ocamlc prj1.ml

clean :
	rm -f *.cmo *.cmi
